Repository googleapis/nodejs-logging-bunyan, pull requests merged in 2019-03, with the labels that each got.

#269 build(ci): use node10 for system-test and samples-test
  .kokoro/continuous/node10/docs.cfg
  .kokoro/continuous/node10/lint.cfg
  .kokoro/continuous/node10/samples-test.cfg
  .kokoro/continuous/node10/system-test-grpcjs.cfg
  .kokoro/continuous/node10/system-test.cfg
  .kokoro/presubmit/node10/docs.cfg
  .kokoro/presubmit/node10/lint.cfg
  .kokoro/presubmit/node10/samples-test.cfg
  .kokoro/presubmit/node10/system-test-grpcjs.cfg
  .kokoro/presubmit/node10/system-test.cfg
Labels: cla: yes

#268 build: update release configuration
  .kokoro/release/publish.cfg
  synth.metadata
Labels: cla: yes

#270 build: Add docuploader credentials to node publish jobs
  .kokoro/release/publish.cfg
  synth.metadata
Labels: cla: yes

#272 chore: allow custom port in samples tests
  samples/express.js
  samples/system-test/express.test.js
Labels: cla: yes

#273 Release @google-cloud/logging-bunyan v0.10.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes

#281 build: use per-repo npm publish token
  .kokoro/release/publish.cfg
Labels: automerge, cla: yes

#279 Release @google-cloud/logging-bunyan v0.10.1
  CHANGELOG.md
  package.json
  samples/package.json
Labels: automerge, autorelease: pending, cla: yes

#282 chore: use wombat to publish to npm
  .kokoro/publish.sh
Labels: cla: yes
