Repository googleapis/nodejs-logging-bunyan, pull requests merged in 2020-11, with the labels that each got.

#498 build(node): add KOKORO_BUILD_ARTIFACTS_SUBDIR to env
  .kokoro/trampoline_v2.sh
  synth.metadata
Labels: api: logging, automerge, cla: yes, context: full

#499 chore: add generated files bot config
  .github/generated-files-bot.yml
Labels: api: logging, cla: yes, priority: p2, type: process

#500 chore: debrand Stackdriver Logging into Cloud Logging
  .readme-partials.yml
  package.json
  samples/quickstart.js
  samples/system-test/express.test.js
Labels: api: logging, cla: yes, priority: p2, type: cleanup

#501 docs: update product branding
  README.md
  samples/README.md
  synth.metadata
Labels: api: logging, cla: yes, context: none

#502 chore: add blunderbuss
  .github/blunderbuss.yml
Labels: api: logging, cla: yes, priority: p2

#506 docs: spelling correction for "targetting"
  README.md
  synth.metadata
Labels: api: logging, automerge, cla: yes, context: full
