Repository googleapis/nodejs-logging-bunyan, pull requests merged in 2020-07, with the labels that each got.

#459 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: automerge, cla: yes

#461 chore: delete Node 8 presubmit tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes

#460 build: typo in gitattribute
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full, gitattribute.*, in

#465 build: fix typo in publish
  .kokoro/publish.sh
  synth.metadata
Labels: automerge, cla: yes, context: partial

#466 chore: add config files for cloud-rad for node.js
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  api-extractor.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#467 chore: add dev dependencies for cloud-rad ref docs
  package.json
Labels: automerge, cla: yes

#468 build: rename _toc to toc
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: automerge, cla: yes, context: full, kokoro:run

#472 build: move gitattributes files to node templates
  .gitattributes
  synth.metadata
Labels: cla: yes, context: full

#473 chore(node): fix kokoro build path for cloud-rad
  .kokoro/release/docs-devsite.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full
