Repository googleapis/nodejs-logging-bunyan, pull requests merged in 2021-06, with the labels that each got.

#542 chore(nodejs): remove api-extractor dependencies
  package.json
Labels: api: logging, automerge, cla: yes

#543 feat: add spanId and traceSampled logic
  src/index.ts
  src/middleware/express.ts
  src/types/core.d.ts
  system-test/test-middleware-express.ts
  test/index.ts
Labels: api: logging, cla: yes, priority: p2, type: feature request

#549 chore: update blunderbuss.yml
  .github/blunderbuss.yml
Labels: api: logging, cla: yes
